# Generated by Django 4.2.1 on 2023-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='media.stockmedia'),
        ),
    ]
