# Generated by Django 4.2.1 on 2023-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmedia',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='stock_media'),
        ),
        migrations.AddField(
            model_name='stockmedia',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
